from time import sleep
sleep(0.2)
print("███████╗██╗███╗   ██╗██████╗    ██╗   ██╗███████╗███████╗██████╗ ")
sleep(0.2)
print("██╔════╝██║████╗  ██║██╔══██╗   ██║   ██║██╔════╝██╔════╝██╔══██╗")
sleep(0.2)
print("█████╗  ██║██╔██╗ ██║██║  ██║   ██║   ██║███████╗█████╗  ██████╔╝")
sleep(0.2)
print("██╔══╝  ██║██║╚██╗██║██║  ██║   ██║   ██║╚════██║██╔══╝  ██╔══██╗")
sleep(0.2)
print("██║     ██║██║ ╚████║██████╔╝██╗╚██████╔╝███████║███████╗██║  ██║Crated by ./al3tiby0")
sleep(0.2)
print("╚═╝     ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝Ig: @_wwi")
print("")
user = input("Enter usrename ->")
print("Searching for the user.....")
print("")
sleep(3)
print("These are the pages found for the user:")
sleep(0.9)
print("")
print("Instagram: ""https://instagram.com/"+user)
sleep(0.1)
print("")
print("Twitter: ""https://twitter.com/"+user)
sleep(0.1)
print("")
print("Snapchat: ""https://www.snapchat.com/add/"+user)
sleep(0.1)
print("")
print("Tik tok: ""https://www.tiktok.com/@"+user)
sleep(0.1)
print("")
print("Facebook: ""https://www.facebook.com/"+user+"/")
